// Created by Bracken Asay on 4/2/25.
// Note: Junie (JetBrains AI) contributed code to this file on 2025-09-24.

#pragma once

#include "../../AppEngine/AppEngine.h"
#include "../PopupWindows/PianoRollComponents/PianoRollEditor.h"
#include "TrackListComponent.h"
#include <juce_gui_basics/juce_gui_basics.h>

class AppEngine;

/**
 * Represents the track editor view, with functionality for adding and deleting tracks.
 * Each track contains a corresponding header, footer, and a series of MIDI clips.
 */
class TrackEditView final : public juce::Component, public juce::MidiKeyboardStateListener, public juce::MenuBarModel
{
public:
    explicit TrackEditView (AppEngine& engine);
    ~TrackEditView() override;

    void setupButtons();
    void paint (juce::Graphics&) override;
    void resized() override;
    bool keyPressed (const juce::KeyPress&) override;
    bool keyStateChanged(bool isKeyDown) override;

    // --- MenuBarModel overrides ---
    juce::StringArray getMenuBarNames() override;
    juce::PopupMenu getMenuForIndex (int topLevelMenuIndex, const juce::String& menuName) override;
    void menuItemSelected (int menuItemID, int topLevelMenuIndex) override;

    // MidiKeyboardStateListener
    void handleNoteOn (juce::MidiKeyboardState*, int midiChannel, int midiNoteNumber, float velocity) override;
    void handleNoteOff(juce::MidiKeyboardState*, int midiChannel, int midiNoteNumber, float /*velocity*/) override;

    /**
     * Called when Back is pressed. Should return to home screen.
     */
    std::function<void()> onBack;
    std::function<void()> onOpenMix;

    void showPianoRoll(te::MidiClip* clip);
    void hidePianoRoll();

    int getPianoRollIndex() const;

    class PianoRollResizerBar final : public juce::StretchableLayoutResizerBar
    {
    public:
        PianoRollResizerBar (juce::StretchableLayoutManager* layoutToUse, int itemIndexInLayout, bool isBarVertical);
        ~PianoRollResizerBar() override;

        void hasBeenMoved() override;
        void mouseDrag (const juce::MouseEvent& event) override;
    };

private:
    void injectNoteMessage (const juce::MidiMessage& msg);

    juce::Array<char> noteKeys{ 'A', 'W', 'S', 'E', 'D', 'F', 'T', 'G', 'Y', 'H', 'U', 'J', 'K', 'O', 'L' };

    std::shared_ptr<AppEngine> appEngine;
    std::unique_ptr<TrackListComponent> trackList;
    juce::Viewport viewport;

    // [Generated by Junie] Shared note state for any on-screen piano and QWERTY keyboard mapping.
    // We listen to this to receive note on/off and route them to the selected track.
    juce::MidiKeyboardState midiKeyboardState;

    // [Generated by Junie] Visual piano keyboard which also maps computer keys to notes.
    // std::unique_ptr<juce::MidiKeyboardComponent> midiKeyboard;
    // Base octave for QWERTY mapping; adjusted with Z/X keys.
    int keyboardBaseOctave = 4;

    std::unique_ptr<PianoRollEditor> pianoRoll;
    juce::StretchableLayoutManager verticalLayout;
    std::unique_ptr<PianoRollResizerBar> resizerBar;
    int pianoRollTrackIndex = -1;
    bool pianoRollVisible = false;

    double pixelsPerSecond = 100.0;
    te::TimePosition viewStart = 0s;

    // Shared MidiKeyboardState for receiving/performance note events.
    // --- Top Bar Components ---
    std::unique_ptr<juce::MenuBarComponent> menuBar;

    // Center controls
    juce::Label bpmLabel, clickLabel;
    juce::ShapeButton playButton { "play", {}, {}, {} };
    juce::ShapeButton stopButton { "stop", {}, {}, {} };
    juce::ShapeButton recordButton { "record", {}, {}, {} };

    // Right side (placeholder)
    juce::TextButton switchButton { "|||" };

    // Private helper methods for menu actions
    void showOutputDeviceSettings() const;
    void showNewEditMenu() const;
    void showOpenEditMenu() const;

    juce::TextButton backButton { "Back" }, newEditButton { "New" },
        openEditButton { "Open Edit" }, newTrackButton { "New Track" }, outputButton { "Output Device" },
        mixViewButton { "Mix View" };
};